### ISSUE TITLE
gradle_scripts directory purpose?

### ISSUE THREAD

**Issue by seato** [DheerendraRathor/Arcanist-Android-Lint#1]
Your last couple of lines in the README have

```
- Include `app/config` and `app/gradle_scripts`  in your module root
...
- Edit your `app/build.gradle` and include these lines as per your requirements
  - `apply from: 'gradle_scripts/checkstyle.gradle`
  - `apply from: 'gradle_scripts/checkstyle.gradle'`
  - `apply from: 'gradle_scripts/pmd.gradle'`
```

Are you saying that we need to move our existing gradle scripts into `gradle_scripts`? Is this directory used anywhere else? I don't see it being referenced so I get the feeling that if our normal build.gradle works with wherever we defined our gradle scripts to be then we can do away with it.

I tried not putting my quality control gradle scripts in that directory and everything seems to work just fine.

**Comment by DheerendraRathor** [comment]
Sorry for late reply.

`gradle_scripts` directory was created to keep all lint related gradle scripts in one folder. You're free to use any convention you want. You can move checkstyle and pmd gradle scripts to your existing directory. Just make sure you're including these scripts (checkstyle, pmd and findbugs) in your main `build.gradle`.

Hope this helps :-)

**Comment by deepakwv** [comment]
i have done all setup but when i run arc lint command it show : (Usage Exception: No lint engine is configured for this project. Create an '.arclint' file, or configure an advanced engine with 'lint.engine' in '.arcconfig')

**Comment by seato** [comment]
@deepakwv This is a separate issue, would you open up a different issue for this conversation?

**Comment by seato** [comment]
Thanks for the quick response @DheerendraRathor. I just wanted to verify that I wasn't breaking anything by ignoring that part of the README.
