### ISSUE TITLE
how to run arc lint?

### ISSUE THREAD

**Issue by deepakwv** [DheerendraRathor/Arcanist-Android-Lint#2]
i have done all setup but when i run arc lint command it show : (Usage Exception: No lint engine is configured for this project. Create an '.arclint' file, or configure an advanced engine with 'lint.engine' in '.arcconfig')

**Comment by DheerendraRathor** [comment]
You need to add `.arclib` in your `.arcconfig` and also you need to add `android` linter in your `.arclint`. Please check sample `.arclint` and `.arcconfig` included in this repo.

**Comment by deepakwv** [comment]
I done all setup , but dont know how arc lint work.

**Comment by DheerendraRathor** [comment]
can you post the exact error you're getting with `arc lint --trace`?

**Comment by deepakwv** [comment]
Rockss-iMac-9:CRMApp mercury-five$ arc lint --trace
 ARGV  '/Applications/MAMP/htdocs/oferproject/arcanist/bin/../scripts/arcanist.php' 'lint' '--trace'
 LOAD  Loaded "phutil" from "/Applications/MAMP/htdocs/oferproject/libphutil/src".
 LOAD  Loaded "arcanist" from "/Applications/MAMP/htdocs/oferproject/arcanist/src".
Config: Reading user configuration file "/Users/rocks/.arcrc"...
Config: Did not find system configuration at "/etc/arcconfig".
Working Copy: Reading .arcconfig from "/Volumes/data/Applications/CRMApp_Repo/CRMApp/.arcconfig".
Working Copy: Path "/Volumes/data/Applications/CRMApp_Repo/CRMApp/CRMApp" is part of `git` working copy "/Volumes/data/Applications/CRMApp_Repo/CRMApp".
Working Copy: Project root is at "/Volumes/data/Applications/CRMApp_Repo/CRMApp".
Config: Did not find local configuration at "/Volumes/data/Applications/CRMApp_Repo/CRMApp/.git/arc/config".

> > > [0] <exec> $ git rev-parse --verify HEAD^
> > > <<< [0] <exec> 10,011 us
> > > [1] <exec> $ git rev-parse --abbrev-ref --symbolic-full-name '@{upstream}'
> > > <<< [1] <exec> 7,972 us
> > > [2] <exec> $ git cat-file -t 'origin/master'
> > > <<< [2] <exec> 7,300 us
> > > [3] <exec> $ git merge-base 'origin/master' HEAD
> > > <<< [3] <exec> 7,549 us
> > > [4] <exec> $ git diff --no-ext-diff --no-textconv --raw '5f29163105a0533bf3139492bafd6686f51d7426' --
> > > <<< [4] <exec> 10,939 us
> > > [5] <exec> $ git diff --no-ext-diff --no-textconv --raw 'HEAD' --
> > > [6] <exec> $ git ls-files --others --exclude-standard
> > > <<< [6] <exec> 10,720 us
> > > <<< [5] <exec> 12,181 us
> > > [7] <exec> $ git diff-files --name-only
> > > <<< [7] <exec> 7,761 us
> > > [8] <exec> $ git diff --no-ext-diff --no-textconv --no-color --src-prefix=a/ --dst-prefix=b/ -U32767 -M -C '5f29163105a0533bf3139492bafd6686f51d7426' --
> > > <<< [8] <exec> 11,042 us
> > > Examining paths for linter 'chmod'.
> > > Found 2 matching paths for linter 'chmod'.
> > > Usage Exception: Linter 'android' specifies invalid type 'android'. Available linters are: csharp, chmod, composer, filename, xhpast, csslint, gjslint, coffeelint, cppcheck, cpplint, flake8, golint, hlint, jshint, jsonlint, jscs, lessc, pep8, php, phpcs, puppet-lint, pyflakes, pylint, rubocop, ruby, generated, json, merge-conflict, nolint, phutil-library, script-and-regex, spelling, text, xml.

[2016-08-17 07:33:51] EXCEPTION: (ArcanistUsageException) Linter 'android' specifies invalid type 'android'. Available linters are: csharp, chmod, composer, filename, xhpast, csslint, gjslint, coffeelint, cppcheck, cpplint, flake8, golint, hlint, jshint, jsonlint, jscs, lessc, pep8, php, phpcs, puppet-lint, pyflakes, pylint, rubocop, ruby, generated, json, merge-conflict, nolint, phutil-library, script-and-regex, spelling, text, xml. at [<arcanist>/src/lint/engine/ArcanistConfigurationDrivenLintEngine.php:55]
arcanist(head=master, ref.master=3aa47195ef08), phutil(head=master, ref.master=9c03af69571f)
  #0 ArcanistConfigurationDrivenLintEngine::buildLinters() called at [<arcanist>/src/lint/engine/ArcanistLintEngine.php:166]
  #1 ArcanistLintEngine::run() called at [<arcanist>/src/workflow/ArcanistLintWorkflow.php:334]
  #2 ArcanistLintWorkflow::run() called at [<arcanist>/scripts/arcanist.php:394]

**Comment by DheerendraRathor** [comment]
Have you added `"phutil_libraries": [
    ".arclib"
  ]` in your .arcconfig? 
Can you post your .arcconfig file here?

**Comment by deepakwv** [comment]
{
  "phabricator.uri" : "https://test.test.com",
  "repository.callsign" : "REPO",
  "phutil_libraries": [
    ".arclib"
  ]
}

**Comment by DheerendraRathor** [comment]
Can you try `arc liberate` and then `arc lint --trace`

**Comment by DheerendraRathor** [comment]
Ideally this is how your trace should look

 ARGV  '/Users/dheerendra/.arc/arcanist/bin/../scripts/arcanist.php' 'lint' '--trace'
 LOAD  Loaded "phutil" from "/Users/dheerendra/.arc/libphutil/src".
 LOAD  Loaded "arcanist" from "/Users/dheerendra/.arc/arcanist/src".
Config: Reading user configuration file "/Users/dheerendra/.arcrc"...
Config: Did not find system configuration at "/etc/arcconfig".
Working Copy: Reading .arcconfig from "/Users/dheerendra/Code/safe-android/.arcconfig".
Working Copy: Path "/Users/dheerendra/Code/safe-android" is part of `git` working copy "/Users/dheerendra/Code/safe-android".
Working Copy: Project root is at "/Users/dheerendra/Code/safe-android".
Config: Did not find local configuration at "/Users/dheerendra/Code/safe-android/.git/arc/config".
_**Loading phutil library from '/Users/dheerendra/Code/safe-android/.arclib'...**_

> > > [0] <exec> $ git rev-parse --verify HEAD^
> > > <<< [0] <exec> 18,377 us

Note the highlighted line in italics and bold. It is missing from your trace.

**Comment by deepakwv** [comment]
Rockss-iMac-9:CRMApp mercury-five$ arc liberate
Done.

**Comment by deepakwv** [comment]
where should i add .arclib folder?

**Comment by deepakwv** [comment]
it working now i got new issue

 EXCEPTION: (PhutilAggregateException) Some linters failed:
    - ArcanistUsageException: Gradle does not appear to be available on the path. at [<arcanist>/src/lint/engine/ArcanistLintEngine.php:274]
arcanist(head=master, ref.master=3aa47195ef08), libarcandroid(head=master, ref.master=5f29163105a0), phutil(head=master, ref.master=9c03af69571f)
  #0 <#2> ArcanistAndroidLinter::getGradlePath() called at [<libarcandroid>/lint/ArcanistAndroidLinter.php:183]
  #1 <#2> ArcanistAndroidLinter::runGradle(string) called at [<libarcandroid>/lint/ArcanistAndroidLinter.php:132]
  #2 <#2> ArcanistAndroidLinter::lintPath(string) called at [<arcanist>/src/lint/engine/ArcanistLintEngine.php:577]
  #3 <#2> ArcanistLintEngine::executeLinterOnPaths(ArcanistAndroidLinter, array) called at [<arcanist>/src/lint/engine/ArcanistLintEngine.php:535]
  #4 <#2> ArcanistLintEngine::executeLintersOnChunk(array, array) called at [<arcanist>/src/lint/engine/ArcanistLintEngine.php:473]
  #5 <#2> ArcanistLintEngine::executeLinters(array) called at [<arcanist>/src/lint/engine/ArcanistLintEngine.php:216]
  #6 ArcanistLintEngine::run() called at [<arcanist>/src/workflow/ArcanistLintWorkflow.php:334]
  #7 ArcanistLintWorkflow::run() called at [<arcanist>/scripts/arcanist.php:394]

**Comment by DheerendraRathor** [comment]
In your project root. In the same directory as of .arcconfig

**Comment by deepakwv** [comment]
i have already added 

```
apply from: 'gradle_scripts/checkstyle.gradle'
apply from: 'gradle_scripts/pmd.gradle'
apply from: 'gradle_scripts/findbugs.gradle'
```

in my app/build.gradle

**Comment by DheerendraRathor** [comment]
Add gradle and android to your PATH variable. http://apple.stackexchange.com/questions/201290/adding-gradle-to-path

**Comment by deepakwv** [comment]
Thanks for your support.
I placed file in wrong module. its working now.
